### ISSUE TITLE
Travis-ci builds fail out of the box due to missing script 'test-on-travis'

### ISSUE THREAD

**Issue by jensim** [ericmdantas/generator-ng-fullstack#174]
https://travis-ci.org/jensim/myStreamWeb

```
0.40s$ npm run-script test-on-travis
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v5.11.1/bin/node" "/home/travis/.nvm/versions/node/v5.11.1/bin/npm" "run-script" "test-on-travis"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! missing script: test-on-travis
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/jensim/myStreamWeb/npm-debug.log
The command "npm run-script test-on-travis" failed and exited with 1 during .
Your build has been stopped.
```

My .yo-rc.json:

```
{
  "generator-ng-fullstack": {
    "username": "jensim",
    "appName": "myStreamJS",
    "stack": "fullstack",
    "server": "node",
    "client": "ng2",
    "transpilerServer": "typescript",
    "secure": true,
    "differentStaticServer": false
  }
}
```

**Comment by ericmdantas** [comment]
Hello, @jensim. Thanks for pointing it out.

I moved some things around and might've forgotten about this one.

Can you please change the content of the travis file for the following:

```yaml
language: node_js

node_js:
  - "stable"

before_script:
  - npm install -g typings typescript istanbul gulp-cli mocha
  - typings install
  - tsc

script:
  - npm run test-server

services: mongodb
```

Just to see if travis didn't change a few things that used to work.

Also, keep in mind that if you're testing ng2 too, the build will fail because of #101.
